ALTER TABLE users
  ADD COLUMN IF NOT EXISTS nps_reminder_1_sent_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS nps_reminder_2_sent_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS nps_reminder_3_sent_at TIMESTAMPTZ;
